version: '3.8'

networks:
    vouprapraia:
        driver:
            bridge
services:
    nginx:
        container_name: nginx-vpp
        image: nginx:latest
        restart: always
        expose:
            - "555"
        networks:
            - vouprapraia
        volumes:
            - ./html:/var/www/html
            - ./logs:/var/log/nginx/
            - ./sites-enabled:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
        container_name: phpfpm-vpp
        image: php:7.4-fpm
        expose:
            - "9000"
        networks:
            - vouprapraia
        restart: always
        volumes:
            - ./html:/var/www/html
    mysql:
        container_name: mysql-vpp
        image: mysql:latest
        expose:
            - "3306"
        networks:
            - vouprapraia
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
