version: '3.8'
services:
    nginx:
        container_name: nginx-01
        image: nginx:latest
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./html:/var/www/html
            - ./logs:/var/log/nginx/
            - ./sites-enabled:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
        container_name: php-fpm-01
        image: php:7.4-fpm
        expose:
            - "9000"
        restart: always
        volumes:
            - ./html:/var/www/html
    mariadb:
        container_name: mysql-01
        image: mysql:latest
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
