version: '3.8'
services:
    nginx:
        container_name: vpp_nginx
        image: nginx:latest
        restart: always
        expose:
            - "80"
        volumes:
            - /var/zztop/vouprapraia/html:/var/www/html
            - /var/zztop/vouprapraia/logs:/var/log/nginx/
            - /var/zztop/vouprapraia/config:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
        container_name: vpp_phpfpm
        image: php:7.4-fpm
        expose:
            - "9000"
        restart: always
        volumes:
            - /var/zztop/vouprapraia/html:/var/www/html
    mysql:
        container_name: vpp_mysql
        image: mysql:latest
        expose:
            - "3306"
        restart: always
        volumes:
            - /var/zztop/vouprapraia/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: vpp_phpmyadmin
        image: phpmyadmin
        expose:
            - "8888"
        restart: always
        depends_on:
            - mysql
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql